# Generated by Django 5.0 on 2024-05-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='isProfesional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
